---
kind: pipeline
type: docker
name: default

steps:
  - name: 26-slim-build-push
    image: plugins/docker
    settings:
      repo: hentioe/erlang
      username: hentioe
      password:
        from_secret: docker_hub_pass
      dockerfile: 26/slim/Dockerfile
      tags:
        - latest
        - 26-slim
        - 26.1-slim
        - 26.1.1-slim

  - name: 26-alpine-build-push
    image: plugins/docker
    settings:
      repo: hentioe/erlang
      username: hentioe
      password:
        from_secret: docker_hub_pass
      dockerfile: 26/alpine/Dockerfile
      tags:
        - 26-alpine
        - 26.1-alpine
        - 26.1.1-alpine
