when:
  - path:
      exclude: ["README.md", ".drone.yml"]

steps:
  26-slim-build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: hentioe/erlang
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 26/slim/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - latest
        - 26-slim
        - 26.1-slim
        - 26.1.2-slim
    when:
      branch: main
      event: push

  26-alpine-build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: hentioe/erlang
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 26/alpine/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 26-alpine
        - 26.1-alpine
        - 26.1.2-alpine
    when:
      branch: main
      event: push
