steps:
  26-slim-build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: hentioe/erlang
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 26/slim/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - latest
        - 26-slim
        - 26.2-slim
        - 26.2.5-slim
    when:
      branch: main
      event: push

  26-alpine-build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: hentioe/erlang
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 26/alpine/Dockerfile
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 26-alpine
        - 26.2-alpine
        - 26.2.5-alpine
    when:
      branch: main
      event: push

  26-void-build-push:
    image: woodpeckerci/plugin-docker-buildx
    settings:
      repo: hentioe/erlang
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      dockerfile: 26/void/Dockerfile
      context: 26/void/
      platforms: linux/amd64,linux/arm64/v8
      tags:
        - 26-void
        - 26.2-void
        - 26.2.5-void
    when:
      branch: main
      event: push
